name: Bug Report
description: Report a bug or issue with DVD Subtitle Extractor
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue! Please fill out the information below to help diagnose and fix the problem.

  - type: input
    id: version
    attributes:
      label: DVD Subtitle Extractor Version
      description: What version of DVD Subtitle Extractor are you using? (Check Help > About or the installer filename)
      placeholder: "e.g., 2.0.0"
    validations:
      required: true

  - type: input
    id: system
    attributes:
      label: System Information
      description: What operating system and version are you running?
      placeholder: "e.g., Windows 11 24H2, Windows 10 22H2"
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Application Area
      description: Which part of the application has the issue?
      options:
        - DVD/Folder Loading (Step 1)
        - Track Selection (Step 2)
        - Extraction/Demuxing (Step 3)
        - Subtitle Selection (Step 4)
        - OCR/Character Recognition (Step 5)
        - Spell Check (Step 6)
        - File Export (Step 7)
        - Word Spacing (Step 8)
        - Settings/Configuration
        - Startup
        - Other
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Open DVD Subtitle Extractor
        2. Load a subtitle file from...
        3. Click on...
        4. See error
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Current Outcome
      description: What actually happens? Include any error messages or unexpected behavior.
      placeholder: "Describe what you're seeing..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Outcome
      description: What did you expect to happen instead?
      placeholder: "Describe what should have happened..."
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information that might be helpful
      placeholder: "Any additional details..."
    validations:
      required: false
